name: FreeCAD Export and Convert
on:
  push:
    branches:
      - main

jobs:
  export-and-convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install FreeCAD and Assimp
        run: |
          sudo apt-get update
          sudo apt-get install -y freecad assimp-utils
      
      - name: Export STL from FreeCAD
        run: |
          # Assuming your FreeCAD file is named model.FCStd
          # Adjust the filenames and paths as needed
          freecadcmd --run-script "import FreeCAD; import Import; import Mesh; doc = FreeCAD.open('model.FCStd'); Mesh.export([doc.Objects], 'output.stl')"
      
      - name: Convert STL to GLB
        run: |
          assimp export output.stl output.glb
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 3d-models
          path: |
            output.stl
            output.glb

